### ISSUE TITLE
No reference to project that this was based on

### ISSUE THREAD

**Issue by JuanPotato** [JeroenMols/Legofy#1]
https://play.google.com/store/apps/details?id=com.jeroenmols.brickeffect

> Based on Legofy by Juan Potato: https://github.com/JuanPotato/Legofy

Nice app btw

**Comment by JeroenMols** [comment]
First of all thanks! 

I'm not sure what you mean by this issue: I do refer to your project in Google Play, right?

**Comment by JuanPotato** [comment]
I meant for people who see the repository, there's no mention of it here

**Comment by JeroenMols** [comment]
Sorry about that, I missed it completely.
Thanks for letting me know, I added the proper credit now. (Thanks for the inspiration btw!)
